#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Title: artist_title - track_title
# Size: small|smallsquare|medium|mediumsquare|large|largesquare|mega|original

DATAPATH=$BASEPATH/app/lastfm
cd $DATAPATH

LASTFMFILE=$TMPFILE.lastfm

arg_opt=`urldecode_s "$arg_opt"`

get_opt "Title"
local tracktitle="$opt"

local artist=`expr "$tracktitle" : '\(.*\) - .*' \| "$tracktitle" | sed 's/ /+/g'` 
local track=`expr "$tracktitle" : '.* - \(.*\)' \| "$tracktitle" | sed 's/ /+/g'` 
local request="http://www.last.fm/music/$artist/_/$track"

get_opt "Size"
local size=largesquare
case $opt in
  small|smallsquare|medium|mediumsquare|large|largesquare|mega|original)
    size=$opt
    ;;
esac

$MSDL -q -o "$LASTFMFILE" -p http --useragent "$USERAGENT" "$request"

if [ -f "$LASTFMFILE" ]; then
  
  local imageurl=`grep LFM.set\(\"Par "$LASTFMFILE" | sed "s/.*image\":{//;s/},.*//;s/.*\"$size\":\"//;s/\".*//;" | sed 's/\\\//g'`
  local buf=`$MSDL --debug -o "$LASTFMFILE" -p http --useragent "$USERAGENT" "$imageurl" 2>&1`
  local type=`echo "$buf" | sed -n '/^[cC]ontent[ -][tT]ype/p' | sed -n '$p' | awk '{ match($0, /[ ;:]+([a-z]+\/[a-z\-]+)[ ;]*.*$/, arr); print arr[1]}'`
  
  echo "Content-type: $type"
  echo
  cat "$LASTFMFILE"
  rm -f "$LASTFMFILE"
fi

