#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

DATAPATH=$BASEPATH/app/collection
cd $DATAPATH

SUBNAME=media

CHANNELFILE=$TMPFILE.channel

arg_opt=`urldecode_s "$arg_opt"`

get_opt "File"
FILE="$opt"

[ -z "$FILE" ] && return 0

if ! expr "$FILE" : '/.*' > /dev/null; then
  FILE="$BASEPATH/$FILE"
fi

get_opt "Column"
if [ -z "$opt" ]; then
  opt=6
fi
COLUMNCOUNT="columnCount=$opt"

get_opt "Start"
if [ -z "$opt" ]; then
  opt=left
fi
STARTITEM="  startitem = \"$opt\";"

echo "Content-type: text/xml"
echo
if [ -x "$XSLTPROC" ]; then
  $XSLTPROC $SUBNAME.xslt "$FILE" | sed '1d' > $CHANNELFILE
else
  awk -f $SUBNAME.awk "$FILE" > $CHANNELFILE
fi
(
  export CHANNELFILE; 
  export COLUMNCOUNT; 
  export STARTITEM;
  template2rss $SUBNAME.xml
  rm -f $CHANNELFILE
)
