#!/bin/sh
DATAPATH=$BASEPATH/app/collection
cd $DATAPATH

CHANNELFILE=$TMPFILE.channel

echo "Content-type: text/xml"
echo
if [ -x "$XSLTPROC" ]; then
  $XSLTPROC video.xslt "$arg_opt" | sed '1d' > $CHANNELFILE
else
  awk -f video.awk "$arg_opt" > $CHANNELFILE
fi
(
  export CHANNELFILE; 
  template2rss video.xml
  rm -f $CHANNELFILE
)
