#!/bin/sh
arg_url='http://www.24video.net/video/filter?time=0&sort=1&theme=0'
PAGEXML='./filter.xml'
PAGEFILE='./filter.html'
DATAPATH='./'
XSLTPROC='xsltproc'

wget -O $PAGEFILE $arg_url 2>/dev/null
if [ -f "$PAGEFILE" ]; then
  pages=`cat $PAGEFILE | grep 'src="/images/arrow_right.gif"/></a></div>' | sed '1d' | sed -r 's/<[^>]*>/~/g;s/~*$//;s/^.*~([0-9]*)$/\1/'`

  if [ "$pages" = "" ]; then
    pages=1
  fi

  cat > $PAGEXML <<EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title> 24video.net </title>
<link>$arg_url</link>
<description> 24video.net </description>
<language>ru</language>
<pages>$pages</pages>
EOF

#if [ -x $XSLTPROC ]; then
  $XSLTPROC --encoding utf-8 --html $DATAPATH/videos.xslt $PAGEFILE 2>/dev/null | sed '1d' >> $PAGEXML
#fi

  cat >> $PAGEXML <<EOF
</channel>
</rss>
EOF

  rm -f $PAGEFILE
fi

if [ -f "$PAGEXML" ]; then
  cat $PAGEXML
  rm -f $PAGEXML
fi