#!/bin/sh
DATAPATH=$BASEPATH/app/shoutcast
cd $DATAPATH

arg_opt=`urldecode_s $arg_opt`
get_opt "Station-id"
STATION_ID="$opt"
get_opt "Station-name"
STATION_NAME="$opt"
get_opt "Station-br"
STATION_BR="$opt"
get_opt "Station-mt"
STATION_MT="$opt"
get_opt "Station-genre"
STATION_GENRE="$opt"

STATION_PLS="$CACHEPATH/shoutcast.$STATION_ID.cache.pls"

CHANNELFILE=$TMPFILE.channel

TIMELIFE=3600

let tsttime=`date +%s`-$TIMELIFE

REFRESHCACHE=yes
if [ -f "$STATION_PLS" ]; then
  if [ `date +%s -r "$STATION_PLS"` -gt $tsttime ]; then
    REFRESHCACHE=
  fi
fi

if [ $REFRESHCACHE ]; then
  rm -f "$STATION_PLS"
  $WGET -q -O "$STATION_PLS" "http://yp.shoutcast.com/sbin/tunein-station.pls?id=${STATION_ID}"
fi

if [ -f "$STATION_PLS" ]; then
  local numberofentries=`sed -ne '/^numberofentries=/p' $STATION_PLS | awk -F= '{print $2}'`
  local tit=dummy
  local index=0

  while [ -n "$tit" ]; do
      let index=$index+1
      tit=`sed -ne "/^Title$index=\(.*- 0\/[0-9]*\)/p" $STATION_PLS`
  done

  local stream_url=`sed -ne "/^File$index=/p" $STATION_PLS | sed -e "s/^File$index=//"`
  if [ -z "$stream_url" ]; then
      let index=$index-1
      stream_url=`sed -ne "/File$index=/p" $STATION_PLS | sed -e "s/File$index=//"`
  fi
  
  STREAMDAT=/tmp/cached/stream.dat
  echo "$stream_url" > $STREAMDAT       # request_url
  echo "" >> $STREAMDAT                 # request_options
  echo "$stream_url" >> $STREAMDAT      # stream_url
  echo "http://127.0.0.1/cgi-bin/translate?stream,Content-type:${STATION_MT},`urlencode_s $stream_url`" >> $STREAMDAT # [renderer_]url
  echo "$STATION_MT" >> $STREAMDAT      # stream_type
  echo "" >> $STREAMDAT                 # stream_status_url
  echo "" >> $STREAMDAT                 # stream_current_song
  echo "$STATION_GENRE" >> $STREAMDAT   # stream_genre
  echo "$STATION_BR" >> $STREAMDAT      # stream_bitrate
  echo "$STATION_NAME" >> $STREAMDAT    # stream_title
  echo "1" >> $STREAMDAT                # no_renderer_control
  
  echo "Content-type: text/xml"
  echo
  cat $BASEPATH/rss/xspf/audioRenderer.rss
fi