#!/bin/sh
DATAPATH=$BASEPATH/app/shoutcast
cd $DATAPATH

GENRE=`urldecode_s "$arg_opt"`

GENRELIST="$CACHEPATH/shoutcast.`echo -n \"$GENRE\" | sed 's/\//_/g'`.cache"
TEMPDL=$TMPFILE.dl

CHANNELFILE=$TMPFILE.channel

TIMELIFE=3600

let tsttime=`date +%s`-$TIMELIFE

REFRESHCACHE=yes
if [ -f "$GENRELIST" ]; then
  if [ `date +%s -r "$GENRELIST"` -gt $tsttime ]; then
    REFRESHCACHE=
  fi
fi

if [ $REFRESHCACHE ]; then
  $WGET -q -O "$TEMPDL" "http://www.shoutcast.com:80/sbin/newxml.phtml?genre=${arg_opt}"
  if [ -f "$TEMPDL" ]; then
    mv -f "$TEMPDL" "$GENRELIST"
  fi
fi

if [ -f "$GENRELIST" ]; then
  TITLE="Shoutcast Radio - `escapeXML \"$GENRE\"`"
  echo "Content-type: text/xml"
  echo
  awk -v title="$TITLE" -f shoutcast_genre.awk "$GENRELIST" > $CHANNELFILE
  (
    export CHANNELFILE; 
    template2rss shoutcast_genre.xml
    rm -f $CHANNELFILE
  )
fi