#!/bin/sh

TITLE='Hello, world!'

cat <<EOF
Content-type: text/xml

<application title="$TITLE">
<arg>$arg_opt</arg>
`echo "<echo/>"`
<export><![CDATA[`export`]]></export>
<set><![CDATA[`set`]]></set>
</application>
EOF
