#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/radiotime
cd $DATAPATH

. ./settings

local OPML=$TMPFILE.opml
local INITSCRIPT=$TMPFILE.channel

get_opt "Link"
local LINK="$opt"

get_opt "Key"
local KEY="$opt"

get_opt "Text"
local TEXT="$opt"

get_opt "Type"
local TYPE="$opt"

$WGET -q -O "$OPML" "$LINK"

if [ -f "$OPML" ]; then
  if [ -x "$XSLTPROC" ]; then
    $XSLTPROC --stringparam self "$LINK" --stringparam type "$TYPE" --stringparam key "$KEY" --stringparam text "$TEXT" browse.xslt "$OPML" | sed '1d' > $INITSCRIPT
  else
    awk -f browse.awk "$OPML" > $INITSCRIPT
  fi

  (
    export INITSCRIPT;
    template2rss browse.xml | printContent "application/rss+xml"
    rm -f "$INITSCRIPT"
    rm -f "$OPML"
  )
fi